export const diagnosticStatuses = ["Strong current evidence", "Developing appropriately", "Needs focused attention", "Insufficient information", "Potential concern", "Context-dependent"] as const;
export type DiagnosticStatus = (typeof diagnosticStatuses)[number];

export type DiagnosticDimension = {
  id: string;
  title: string;
  prompt: string;
  investigate: string[];
  risk: string;
  immediate: string;
  longer: string;
  caution: string;
  student: string;
};

export const diagnosticDimensions: DiagnosticDimension[] = [
  { id: "academic", title: "Academic preparation", prompt: "Record evidence across core subjects, grades, trends, and preparation for possible fields.", investigate: ["What does the school offer?", "Which subjects show durable strength or difficulty?"], risk: "A GPA can obscure course context and subject-level patterns.", immediate: "Review the transcript with the school profile and grading scale.", longer: "Build a sustainable sequence that supports broad and field-relevant preparation.", caution: "Do not translate preparation into an admission prediction.", student: "We are reviewing what your courses and grades show about preparation, in the context of your school." },
  { id: "rigor", title: "Course rigor", prompt: "Compare course choices with availability, prerequisites, workload, and wellbeing.", investigate: ["Which advanced courses were available?", "What level of challenge is sustainable?"], risk: "Counting advanced labels can reward access and overload rather than preparation.", immediate: "Map current choices against available sequences.", longer: "Plan future rigor with prerequisites, interests, and health in view.", caution: "More advanced courses are not always a better plan.", student: "Appropriate rigor means meaningful challenge you can sustain—not the largest possible course count." },
  { id: "testing", title: "Testing status", prompt: "Record diagnostics, official scores, dates, access needs, and school-specific policies.", investigate: ["Which test format fits better?", "Which policies are current for the list?"], risk: "A score may be mistaken for a universal threshold.", immediate: "Choose or revise a bounded testing plan.", longer: "Recheck policies before submission and stop when more testing is not useful.", caution: "Never infer an admission probability from a score.", student: "Testing is one piece of evidence; we will use a reasonable plan and current policies." },
  { id: "direction", title: "Intellectual direction", prompt: "Record questions, reading, making, or learning the student pursues beyond assignments.", investigate: ["What question keeps returning?", "What work continues without an external reward?"], risk: "A polished label can conceal weak genuine interest.", immediate: "Conduct an intellectual-curiosity interview.", longer: "Support accessible, sustained inquiry without manufacturing a project.", caution: "Do not prescribe an artificial ‘spike.’", student: "We are looking for real questions and interests, not a manufactured academic identity." },
  { id: "engagement", title: "Sustained engagement", prompt: "Record duration, time, responsibility, employment, care, and reasons for continuing.", investigate: ["Which commitment matters most?", "Who relies on the student?"], risk: "Activity count can erase depth and responsibilities outside school clubs.", immediate: "Complete an activity inventory with accurate time and context.", longer: "Prioritize commitments that support real learning or contribution.", caution: "Do not discount paid work or family care.", student: "Sustained responsibility matters more than collecting titles." },
  { id: "initiative", title: "Initiative and contribution", prompt: "Record specific problems noticed, actions taken, people served, and outcomes without exaggeration.", investigate: ["What changed because of the student’s work?", "What did the student decide or build?"], risk: "Leadership titles may be mistaken for evidence of contribution.", immediate: "Replace labels with concrete actions and verified context.", longer: "Develop responsibility through existing genuine commitments.", caution: "Do not create organizations for optics.", student: "We will describe what you actually did and learned, not inflate a title." },
  { id: "communication", title: "Communication readiness", prompt: "Assess factual accuracy, reflection, student voice, and ability to explain choices.", investigate: ["Can the student explain the record in their own words?", "What context remains unclear?"], risk: "Adult-edited language can sound polished but lose credibility and ownership.", immediate: "Identify unclear or repeated parts of the application story.", longer: "Practice reflection and student-led revision.", caution: "Question and teach; do not ghostwrite.", student: "Your application should be accurate and sound like you." },
  { id: "recommendations", title: "Recommendation readiness", prompt: "Record possible recommenders, firsthand evidence, school process, and timelines.", investigate: ["Who has observed learning and response to difficulty?", "What are the school’s procedures?"], risk: "The highest grade or most famous teacher may not produce the most specific letter.", immediate: "Identify appropriate recommenders and ask according to school procedure.", longer: "Maintain authentic classroom relationships and provide concise context.", caution: "Never script a recommender’s letter.", student: "Choose people who know how you learn and contribute." },
  { id: "fit", title: "School-fit understanding", prompt: "Record researched preferences across curriculum, place, community, support, and access.", investigate: ["Which preferences are evidence-based?", "What tradeoffs remain?"], risk: "Prestige or campus impressions can substitute for educational research.", immediate: "Complete a college-fit questionnaire for current candidates.", longer: "Test fit hypotheses through deeper research and comparison.", caution: "Use fit to generate questions, not declare a perfect match.", student: "Fit includes how you will learn, live, find support, and belong." },
  { id: "financial", title: "Financial planning", prompt: "Record family range, net price calculator results, forms, deadlines, and borrowing concerns.", investigate: ["What annual range is workable?", "Which aid assumptions need verification?"], risk: "Sticker price, net price, and final aid may be confused.", immediate: "Run official net price calculators and identify aid requirements.", longer: "Maintain financially likely options and compare full offers.", caution: "This tool does not provide individualized financial, legal, or tax advice.", student: "Affordability is part of college fit and should be planned early." },
  { id: "execution", title: "Application execution", prompt: "Record list balance, deadlines, writing status, forms, and quality-control needs.", investigate: ["Which pieces are blocked?", "Are regular applications progressing before early results?"], risk: "Deadline pressure can create factual errors and loss of student voice.", immediate: "Build a complete calendar with owners and internal deadlines.", longer: "Use quality control and portal verification for every submission.", caution: "Do not sacrifice accuracy to submit early.", student: "A strong process is accurate, timely, and leaves room for your own revision." },
  { id: "context", title: "Context requiring explanation", prompt: "Record only relevant opportunity, care, work, health, access, language, transportation, or family context.", investigate: ["What affected opportunity or performance?", "What is necessary for a reader to interpret the record?"], risk: "Important context may be omitted, exaggerated, or turned into an exploitative narrative.", immediate: "Identify factual, relevant context and the appropriate application location.", longer: "Coordinate accurate documentation with school professionals when needed.", caution: "Collect the minimum necessary and protect privacy.", student: "Context helps a reader understand your choices; it should be accurate and shared only where useful." },
];
