import { glossarySchema, validateCollection, type GlossaryEntry } from "./schema";

type Seed = [term: string, definition: string, whyItMatters: string, caution: string, related?: string[]];

const seeds: Seed[] = [
  ["Holistic review", "An application-reading approach that considers multiple parts of a student’s record together rather than applying one numerical cutoff.", "It explains why transcript, activities, writing, recommendations, context, and institutional needs interact.", "Holistic does not mean every factor has equal weight or that admission is predictable.", ["Contextual review", "Institutional priorities"]],
  ["Contextual review", "Interpretation of achievement and choices in light of opportunity, school setting, responsibilities, access, and relevant circumstances.", "The same course or activity record can carry different meaning in different contexts.", "Context is not a mechanical bonus and should not be exaggerated.", ["School profile", "Course rigor"]],
  ["School profile", "A document from a secondary school explaining curriculum, grading, course availability, demographics, and other local context.", "Admission readers use it to understand what a transcript means within that school.", "Consultants should not assume every profile contains the same information.", ["Contextual review", "Course rigor"]],
  ["Course rigor", "The level of academic challenge in a student’s schedule relative to what is available and appropriate.", "It helps readers evaluate preparation and choices.", "Rigor is not an AP count and should not justify unsafe overload.", ["School profile", "Weighted GPA"]],
  ["Weighted GPA", "A grade-point average that adds value for some advanced courses under a school’s own rules.", "It may summarize performance and course level within one system.", "Weighting systems differ; do not compare the numbers across schools as though they are standardized.", ["Unweighted GPA", "Course rigor"]],
  ["Unweighted GPA", "A grade-point average calculated without additional points for course level, often on a 4.0 scale.", "It can provide a simplified view of grades.", "It can hide differences in rigor, grading scales, and school context.", ["Weighted GPA", "School profile"]],
  ["Class rank", "A school’s ordering or grouping of students based on its chosen academic calculation.", "Some colleges use rank as one contextual indicator.", "Many schools do not report rank, and methods vary widely.", ["Weighted GPA", "School profile"]],
  ["Early Decision", "A generally binding application plan under which an admitted student agrees to enroll, subject to the institution’s stated terms.", "It affects timing, choice, financial comparison, and other applications.", "Read the exact agreement and financial implications; do not infer an individual admissions boost.", ["Early Action", "Regular Decision"]],
  ["Early Action", "A generally nonbinding early application plan that allows an admitted student to decide later.", "It can provide an earlier decision without the standard ED commitment.", "Restrictions and dates vary by institution.", ["Early Decision", "Restrictive Early Action"]],
  ["Restrictive Early Action", "A nonbinding early plan that limits some other early applications.", "It changes which applications a student may file at the same time.", "The permitted exceptions are institution-specific and must be read directly.", ["Single-Choice Early Action", "Early Action"]],
  ["Single-Choice Early Action", "A label used for a nonbinding early plan that restricts certain other early applications.", "It requires coordinated application strategy.", "Do not assume every institution defines its exceptions the same way.", ["Restrictive Early Action", "Early Decision"]],
  ["Regular Decision", "The standard nonbinding application round with later deadlines and spring decisions.", "It preserves the ability to compare admission and aid offers.", "Deadlines and notification windows vary.", ["Early Decision", "Rolling admission"]],
  ["Rolling admission", "A process in which applications are reviewed and decisions released over an extended period rather than in one batch.", "Earlier completion may matter when space or aid is limited.", "Rolling does not always mean immediate, unrestricted, or guaranteed admission.", ["Regular Decision", "Early Action"]],
  ["Test-required", "A policy requiring specified standardized-testing evidence for the applicable applicant group and cycle.", "It determines what must be submitted for a complete application.", "Eligible tests, exceptions, and cycles vary; verify the official policy.", ["Test-optional", "Test-flexible"]],
  ["Test-optional", "A policy allowing applicants to decide whether to submit certain standardized scores.", "It changes the submission decision, not necessarily how submitted scores are considered.", "It does not mean scores are ignored or that omission is treated identically in every program.", ["Test-required", "Superscore"]],
  ["Test-flexible", "A policy allowing applicants to meet a testing expectation through more than one defined type of exam or credential.", "It may provide alternatives to SAT or ACT submission.", "The accepted alternatives are school-specific; do not use the label without reading the rule.", ["Test-required", "Test-optional"]],
  ["Superscore", "A score-combination method that uses a student’s highest eligible section scores across test dates.", "It can affect reporting and retesting decisions.", "Policies differ by exam, institution, and cycle.", ["Test-optional", "ACT"]],
  ["Demonstrated interest", "Actions an institution may use to understand an applicant’s level of engagement, such as visits or communications where the college states they matter.", "At some colleges it can inform enrollment-interest judgments.", "Many institutions do not consider it; never manufacture contact or assume it is relevant.", ["Yield", "Institutional priorities"]],
  ["Institutional priorities", "Enrollment needs and goals an institution may consider when shaping a class, some of which are not visible to applicants.", "They help explain why many similarly qualified applicants receive different outcomes.", "They cannot be reverse-engineered into a reliable formula.", ["Holistic review", "Yield"]],
  ["Recruited athlete", "An applicant receiving formal support in an institution’s athletic-recruitment process.", "Recruited applicants can have different timelines and institutional context.", "Playing a sport is not the same as being recruited; rules vary by institution and governing body.", ["Institutional priorities"]],
  ["Legacy", "A term generally referring to an applicant with a family relationship to an alumnus or alumna, as defined by an institution.", "Some institutions have historically considered it, while policies are changing.", "Never assume it is considered or decisive; verify current policy and law.", ["Institutional priorities"]],
  ["First-generation student", "A student whose parent or guardian education history fits an institution’s stated first-generation definition.", "It can provide context about access to college knowledge and resources.", "Definitions vary; do not assign the label without the student’s context and the institution’s rule.", ["Contextual review"]],
  ["Common Application", "A shared undergraduate application platform used by many colleges.", "It centralizes common information while allowing college-specific requirements.", "Each college still sets its own deadlines, supplements, and policies.", ["Coalition Application", "Additional Information section"]],
  ["Coalition Application", "A shared college application platform now delivered through Scoir for participating institutions.", "It provides another application pathway at some colleges.", "Participation and requirements can change; verify the institution’s accepted platforms.", ["Common Application"]],
  ["QuestBridge", "A nonprofit program connecting high-achieving students from low-income backgrounds with partner colleges through programs including the National College Match.", "It can change application timing, forms, and financial-aid pathways for eligible students.", "Eligibility and partner requirements are specific; use official QuestBridge and college sources.", ["Need-based aid", "CSS Profile"]],
  ["FAFSA", "The U.S. federal form used to apply for federal student aid and often required for other aid.", "Missing it can affect grants, loans, work-study, and institutional processes.", "Use the official federal site and current-year deadlines; this resource does not give individualized financial advice.", ["CSS Profile", "Need-based aid"]],
  ["CSS Profile", "A financial-aid application administered by College Board and required by some institutions for institutional aid.", "It may collect information beyond the FAFSA.", "Requirements, fees, waivers, and deadlines vary by institution.", ["FAFSA", "Net price"]],
  ["Net price", "The estimated or actual cost after grants and scholarships are subtracted from the institution’s cost of attendance.", "It is more useful than sticker price for affordability planning.", "A calculator result is an estimate, not a final aid offer.", ["Need-based aid", "Merit aid"]],
  ["Need-based aid", "Financial assistance awarded based on an institution’s assessment of financial need.", "It can substantially change net cost.", "Need calculations and aid generosity differ by institution.", ["Net price", "FAFSA"]],
  ["Merit aid", "Scholarship assistance awarded for criteria such as achievement or talent rather than financial need.", "It can affect affordability at institutions that offer it.", "Many highly selective colleges do not award institutional merit aid; verify each policy.", ["Need-based aid", "Net price"]],
  ["Deferral", "An early-round outcome that moves an application to a later review round rather than admitting or denying it immediately.", "It may create a limited opportunity for updates under institutional instructions.", "It is not a promise of later admission and should not halt other applications.", ["Waitlist", "Letter of continued interest"]],
  ["Waitlist", "A post-decision list an institution may use if it later needs to fill spaces in the entering class.", "A student must decide whether to remain available while protecting another enrollment option.", "Movement is uncertain and can have financial or housing implications.", ["Deferral", "Matriculation"]],
  ["Letter of continued interest", "A concise update confirming interest and adding meaningful new information when an institution permits it.", "It can clarify intent after deferral or waitlist.", "Follow instructions, avoid repetition, and do not send repeated pressure messages.", ["Deferral", "Waitlist"]],
  ["Midyear report", "A school-submitted update that commonly includes first-semester or midyear grades and related school information.", "It provides current senior-year academic evidence.", "Requirements and submission processes differ by college and school.", ["Counselor recommendation"]],
  ["Counselor recommendation", "A school counselor’s letter or report providing academic, school, and personal context.", "It can explain curriculum, context, trends, and community participation.", "Students may provide factual context but should not write the counselor’s letter.", ["Teacher recommendation", "School profile"]],
  ["Teacher recommendation", "A letter from a teacher describing firsthand academic engagement, learning habits, and contribution.", "Specific observation can add evidence not visible in grades.", "Choose for knowledge and relevance, not title or prestige.", ["Counselor recommendation", "FERPA waiver"]],
  ["Additional Information section", "An application space for concise context or details that do not fit elsewhere.", "It can clarify disruptions, responsibilities, unusual curriculum, or necessary facts.", "It is not an extra personal essay or a place to repeat achievements.", ["Common Application", "Contextual review"]],
  ["FERPA waiver", "An application choice concerning a student’s future access rights to confidential recommendation materials under U.S. education law.", "Colleges and recommenders often explain how confidentiality supports candid letters.", "Consultants should explain the basic choice and refer legal questions; they should not pressure or provide legal advice.", ["Teacher recommendation"]],
  ["Matriculation", "Formal enrollment as a student at an institution.", "It marks the transition from admission to membership in the entering class.", "Students should follow deposit, withdrawal, transcript, and conduct requirements carefully.", ["Yield"]],
  ["Yield", "The proportion of admitted students who enroll at an institution.", "Institutions use it in enrollment planning.", "It is an institutional measure, not a student fit score or reason to perform interest dishonestly.", ["Demonstrated interest", "Matriculation"]],
];

const rawGlossary: GlossaryEntry[] = seeds.map(([term, definition, whyItMatters, caution, related = []]) => ({
  term,
  slug: term.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
  definition,
  whyItMatters,
  caution,
  related,
}));

export const glossary = validateCollection(glossarySchema, rawGlossary).sort((a, b) => a.term.localeCompare(b.term));
