import { lessonSchema, validateCollection, type Lesson } from "./schema";

const reviewed = "2026-07-10";

function makeLesson(input: Omit<Lesson, "id" | "lastReviewedAt">): Lesson {
  return {
    ...input,
    id: `module-${input.module}`,
    lastReviewedAt: reviewed,
  };
}

const rawLessons: Lesson[] = [
  makeLesson({
    module: 1,
    slug: "role-of-a-consultant",
    title: "The role of a college consultant",
    summary: "Define the work, its ethical boundaries, and success measures that do not depend on prestige outcomes.",
    learningObjectives: ["Separate counseling from tutoring, therapy, legal advice, and application authorship.", "Establish clear student, parent, and consultant responsibilities.", "Explain holistic review without implying control over an outcome."],
    sections: [
      { heading: "What the consultant controls", body: "A consultant can organize information, ask clarifying questions, teach process, identify missing evidence, manage timelines, and help a student revise while preserving the student’s decisions and voice. A consultant cannot control institutional priorities or the decisions of an admission committee." },
      { heading: "A three-party working agreement", body: "The student owns experiences, choices, writing, and timely action. Parents disclose financial boundaries and protect student ownership. The consultant maintains scope, records, source verification, and honest expectations." },
      { heading: "Success beyond prestige", body: "Measure success by thoughtful choices, a balanced affordable list, accurate applications, student ownership, timely execution, and a decision the student can sustain—not by a brand-name admit." },
    ],
    mistakes: ["Promising outcomes or speaking as though effort earns admission.", "Allowing parents or consultants to take over student decisions.", "Operating outside counseling scope when a licensed or school professional is needed."],
    consultantPrompts: ["What will each person own in this process?", "What would a successful process look like without naming a college?"],
    studentFacingExplanation: "I can help you understand the process, make choices, and present your work clearly. I cannot make a college admit you, and the application must remain yours.",
    knowledgeCheck: { question: "Which is an appropriate consultant success measure?", options: ["An Ivy admission", "A balanced, affordable list the student would use", "A parent-written essay completed early"], correctIndex: 1, explanation: "Process quality, fit, affordability, and student ownership are within the counseling relationship; an admission decision is not." },
    relatedTools: ["Student intake questionnaire", "Meeting agenda template", "Ethics"],
  }),
  makeLesson({
    module: 2,
    slug: "how-selective-admissions-works",
    title: "How selective admissions works",
    summary: "Read an application as contextual evidence rather than a points system.",
    learningObjectives: ["Explain holistic and contextual review.", "Connect the transcript, school profile, activities, recommendations, and writing.", "Explain why many qualified applicants are denied."],
    sections: [
      { heading: "The record is read in context", body: "Course choices are interpreted against what the school offers, grade patterns, responsibilities, access, and the student’s educational environment. The same course list can mean different things in different schools." },
      { heading: "Evidence is connected", body: "Academic preparation, intellectual interests, contributions, recommendations, and writing are not independent points. Readers look for credible relationships among them while also considering institutional needs that applicants cannot see or control." },
      { heading: "Qualification is not entitlement", body: "Perfect grades and high testing can demonstrate preparation; neither guarantees admission. At institutions with far more qualified applicants than spaces, denial is not proof that the student failed or lacked worth." },
    ],
    mistakes: ["Treating a high score as an admission threshold.", "Valuing a leadership title without examining contribution.", "Ignoring opportunity, family responsibility, or school context."],
    consultantPrompts: ["What does the school profile help us interpret?", "Which claims in the application are supported across multiple sources?"],
    studentFacingExplanation: "Colleges review what you did in the context of what was available and what responsibilities you carried. Strong credentials show readiness; they do not create a guarantee.",
    knowledgeCheck: { question: "What is the strongest description of contextual review?", options: ["Lowering standards for some students", "Interpreting choices and achievement within opportunity and circumstance", "Adding points for every activity"], correctIndex: 1, explanation: "Context explains what evidence means; it is not a mechanical bonus or penalty." },
    relatedTools: ["Student readiness diagnostic", "Glossary: contextual review"],
  }),
  makeLesson({
    module: 3,
    slug: "academic-planning",
    title: "Academic planning",
    summary: "Review preparation and rigor relative to access while protecting sustainable learning.",
    learningObjectives: ["Conduct a transcript and course-availability review.", "Distinguish weighted GPA conventions from academic preparation.", "Plan field-relevant study without prescribing overload."],
    sections: [
      { heading: "Transcript review sequence", body: "Confirm the school’s grading scale, weighting, course offerings, prerequisites, and graduation requirements. Then review core subjects, rigor relative to availability, grade trends, gaps, and the senior-year plan." },
      { heading: "Rigor is relational", body: "AP, IB, honors, dual enrollment, and advanced courses have meaning only in context. Appropriate challenge is the most demanding program a student can pursue successfully and healthfully—not the largest possible count of labels." },
      { heading: "Preparation by direction", body: "STEM and engineering interests generally require sustained mathematics and laboratory science; humanities and social sciences require strong reading, writing, language, and analytical preparation. Students should retain breadth while developing readiness." },
    ],
    mistakes: ["Comparing weighted GPAs across schools as though scales are identical.", "Sacrificing health or mastery to maximize advanced-course count.", "Treating senior-year courses as irrelevant after application submission."],
    consultantPrompts: ["Which advanced courses were actually available?", "What sequence best prepares this student without creating overload?"],
    studentFacingExplanation: "We will choose courses that challenge you, prepare you for your interests, and remain sustainable. The goal is meaningful learning, not collecting labels.",
    knowledgeCheck: { question: "What should a rigor review begin with?", options: ["A national AP target", "The school’s offerings, prerequisites, and grading context", "The student’s intended ranking"], correctIndex: 1, explanation: "Rigor can only be understood relative to the school’s curriculum and the student’s circumstances." },
    relatedTools: ["Transcript-review checklist", "Course-rigor review", "Roadmap"],
  }),
  makeLesson({
    module: 4,
    slug: "testing-strategy",
    title: "Testing strategy",
    summary: "Build a calm SAT or ACT plan around diagnostic evidence and current institutional policy.",
    learningObjectives: ["Compare SAT and ACT using diagnostic results.", "Plan a bounded testing timeline.", "Verify required, optional, and flexible policies each cycle."],
    sections: [
      { heading: "Choose with evidence", body: "Use full-length, timed diagnostic tests and the student’s experience to choose a primary exam. Consider format, timing, accessibility, schedule, and the opportunity cost of preparation." },
      { heading: "Bound the plan", body: "Set preparation blocks and a limited number of official dates. Repeated testing stops being useful when improvement has plateaued or preparation displaces academics, health, or more meaningful commitments." },
      { heading: "Policy is not permanent", body: "Test-required, test-optional, and test-flexible rules can change by application cycle and may differ across programs. Reopen the official admission page before advising a student or finalizing submission decisions." },
    ],
    mistakes: ["Presenting one score as a universal threshold.", "Assuming test-optional means scores are never considered.", "Carrying a prior-cycle policy forward without verification."],
    consultantPrompts: ["What did the diagnostics reveal about format and timing?", "Which official policy pages must be checked for this list?"],
    studentFacingExplanation: "Testing is one part of your record. We will choose a reasonable plan, verify each college’s current policy, and stop when more testing is no longer the best use of your time.",
    knowledgeCheck: { question: "When should a school-specific testing policy be verified?", options: ["Once when the student enters high school", "For the relevant application cycle and again before submission", "Only if the score is low"], correctIndex: 1, explanation: "Testing policies are time-sensitive and must be tied to the student’s actual cycle." },
    relatedTools: ["Testing plan", "Policy watch"],
  }),
  makeLesson({
    module: 5,
    slug: "extracurricular-development",
    title: "Extracurricular development",
    summary: "Help students move from genuine interest toward skill, initiative, contribution, and reflection.",
    learningObjectives: ["Assess depth without counting activities.", "Recognize employment, care, and local contribution.", "Identify résumé manufacturing and redirect ethically."],
    sections: [
      { heading: "A useful progression", body: "Interest can lead to commitment, skill, initiative, contribution, and reflection. Not every commitment reaches every stage, and no title substitutes for evidence of what the student actually did and learned." },
      { heading: "Contribution has many forms", body: "Employment, caregiving, faith or cultural communities, independent projects, arts, athletics, clubs, research, online work, and community service can all show responsibility. Access and family context shape what is possible." },
      { heading: "Authenticity over theater", body: "Last-minute organizations, purchased research, inflated titles, false time estimates, and pay-to-play credentials weaken trust. Redirect the student toward useful work connected to an existing interest or community need." },
    ],
    mistakes: ["Counting activities instead of examining sustained engagement.", "Discounting paid work or family care.", "Encouraging a nonprofit primarily for application optics."],
    consultantPrompts: ["Who relies on the student and for what?", "What changed because the student stayed involved?"],
    studentFacingExplanation: "Colleges can learn more from honest, sustained responsibility than from a long list of titles. We will describe what mattered and what you contributed without exaggeration.",
    knowledgeCheck: { question: "Which evidence most strengthens an activity description?", options: ["A founder title", "Specific responsibility, action, contribution, and reflection", "A prestigious organization name"], correctIndex: 1, explanation: "Concrete sustained work is more informative than a title or borrowed prestige." },
    relatedTools: ["Activity inventory", "Case: Last-minute nonprofit"],
  }),
  makeLesson({
    module: 6,
    slug: "intellectual-vitality",
    title: "Intellectual vitality",
    summary: "Recognize curiosity and self-directed learning without equating them with expensive programs.",
    learningObjectives: ["Identify credible evidence of independent questions and persistence.", "Generate low-cost examples across disciplines.", "Connect curiosity to reflection rather than performance."],
    sections: [
      { heading: "What to notice", body: "Listen for questions pursued beyond an assignment, reading and making outside class, repeated attempts at a difficult problem, connections across subjects, and a student’s ability to describe how their thinking changed." },
      { heading: "Access is not a prerequisite", body: "A local archive, library book trail, repaired bicycle, neighborhood data set, composition notebook, open-source contribution, community interview, or self-designed experiment can reveal serious inquiry without a branded program." },
      { heading: "Do not stage curiosity", body: "The consultant can help a student notice and document genuine patterns. The consultant should not prescribe artificial projects solely to manufacture an intellectual identity." },
    ],
    mistakes: ["Equating research access with intellectual depth.", "Turning every hobby into an application project.", "Writing a narrative the student cannot explain in their own words."],
    consultantPrompts: ["What question kept returning after the class ended?", "What did the student try when the first approach failed?"],
    studentFacingExplanation: "Curiosity can show up in ordinary places. What matters is the question you pursued, the work you chose to do, and what you learned from it.",
    knowledgeCheck: { question: "Which example can demonstrate intellectual vitality?", options: ["Only university research", "A sustained self-directed investigation using accessible resources", "Any expensive summer course"], correctIndex: 1, explanation: "Intellectual vitality is evidenced by inquiry and sustained thinking, not the price or brand of the setting." },
    relatedTools: ["Intellectual-curiosity interview", "Summer planning worksheet"],
  }),
  makeLesson({
    module: 7,
    slug: "summer-planning",
    title: "Summer planning",
    summary: "Choose purposeful and sustainable summer work without treating branded programs as inherently superior.",
    learningObjectives: ["Generate options across work, care, learning, contribution, projects, and rest.", "Evaluate opportunity cost and affordability.", "Connect a plan to the student’s real priorities."],
    sections: [
      { heading: "Start with constraints and needs", body: "Map work hours, family responsibilities, transportation, cost, health, and desired rest before proposing programs. A good plan is feasible and leaves room for recovery." },
      { heading: "Useful options", body: "Employment, local volunteering, community-college study, arts training, reading, skill building, research, personal projects, and family responsibility can all be meaningful when the student is engaged and reflective." },
      { heading: "Brand is not value", body: "An expensive program is not automatically selective, rigorous, or useful. Compare what the student will actually do, who will guide them, what access it creates, cost, and what they would give up." },
    ],
    mistakes: ["Assuming travel or a university logo makes an experience valuable.", "Ignoring rest and family commitments.", "Choosing an activity only because it sounds impressive."],
    consultantPrompts: ["What must the summer accommodate?", "What will the student be able to do—not merely attend?"],
    studentFacingExplanation: "A strong summer does not need a famous name. It should fit your circumstances and give you a real chance to work, learn, contribute, create, or recover.",
    knowledgeCheck: { question: "What is the best first summer-planning question?", options: ["Which program has the strongest brand?", "What constraints, responsibilities, interests, and recovery needs shape the summer?", "How many activities can fit?"], correctIndex: 1, explanation: "A feasible, student-centered plan begins with context." },
    relatedTools: ["Summer planning worksheet", "Roadmap"],
  }),
  makeLesson({
    module: 8,
    slug: "school-fit-and-research",
    title: "School fit and college research",
    summary: "Research the educational, social, financial, and practical conditions in which a student could thrive.",
    learningObjectives: ["Move beyond rankings to specific fit dimensions.", "Use official and student-life sources critically.", "Turn claims into questions the student can investigate."],
    sections: [
      { heading: "Fit has multiple dimensions", body: "Review academic model, major access, class size, research, location, culture, cost, aid, support, residential life, flexibility, accessibility, belonging, climate, distance, and career preparation." },
      { heading: "Research for consequences", body: "Ask what a curriculum model would require day to day, how a major is entered, where support is located, how housing works, and what affordability looks like after the net price calculator—not whether the website feels impressive." },
      { heading: "Fit is a hypothesis", body: "A comparison generates questions; it does not declare a perfect match. Students should test assumptions through official materials, classes and department pages, conversations, and visits when feasible." },
    ],
    mistakes: ["Using ranking as a substitute for educational research.", "Ignoring cost until after admission.", "Assuming every student at a college has the same experience."],
    consultantPrompts: ["What would this curriculum require from the student each week?", "Which fit claim still needs evidence?"],
    studentFacingExplanation: "College fit includes how you will learn, live, pay, find support, and belong. We use research to ask better questions, not to name one perfect school.",
    knowledgeCheck: { question: "Which belongs in a complete fit review?", options: ["Ranking only", "Academic model, support, community, and affordability", "Acceptance rate only"], correctIndex: 1, explanation: "Fit is educational, social, practical, and financial." },
    relatedTools: ["College-fit questionnaire", "College research worksheet", "Compare"],
  }),
  makeLesson({
    module: 9,
    slug: "balanced-college-list",
    title: "Building a balanced college list",
    summary: "Create academic and financial options the student would genuinely choose.",
    learningObjectives: ["Use high reach, reach, possible, likely, and financially likely categories cautiously.", "Explain why every Ivy remains a high reach.", "Test likely options for affordability and desirability."],
    sections: [
      { heading: "Categories describe uncertainty", body: "List categories are planning language, not probabilities. Every Ivy League institution remains a high reach even for academically exceptional applicants because preparation does not resolve institutional uncertainty." },
      { heading: "A likely must be usable", body: "A likely option should have strong evidence of admission plausibility, be affordable under realistic assumptions, and be a place the student would attend. A school that fails cost or desirability is not a functional likely." },
      { heading: "Diversify the plan", body: "Balance academic selectivity, financial models, geography, campus types, and application timing. Use net price calculators and identify at least one financially likely path before early binding decisions." },
    ],
    mistakes: ["Treating an Ivy as a target or likely.", "Building a prestige-only list.", "Using a statistical category as a promise."],
    consultantPrompts: ["Would the student attend every likely option?", "Which option is financially likely under the family’s real range?"],
    studentFacingExplanation: "A balanced list protects your choices. It includes schools you would be glad to attend across different levels of uncertainty, including options that are realistically affordable.",
    knowledgeCheck: { question: "When is a school a useful likely option?", options: ["When admission seems plausible", "When it is plausible, affordable, and genuinely desirable", "When its ranking is lower"], correctIndex: 1, explanation: "A likely must work academically, personally, and financially." },
    relatedTools: ["Balanced college-list worksheet", "Financial-fit checklist"],
  }),
  makeLesson({
    module: 10,
    slug: "early-application-strategy",
    title: "Early application strategy",
    summary: "Evaluate binding and nonbinding plans through readiness, restrictions, fit, and financial risk.",
    learningObjectives: ["Distinguish ED, EA, restrictive early plans, rolling, and regular decision.", "Assess financial consequences of binding plans.", "Explain why raw early rates are misleading."],
    sections: [
      { heading: "Plans carry different obligations", body: "Early Decision is generally binding; Early Action is generally nonbinding; restrictive or single-choice early plans limit other early applications; rolling admission reviews over a period. The exact institution’s policy controls." },
      { heading: "Readiness before strategy", body: "An early application should be academically, financially, and editorially ready. A calendar advantage does not justify weak senior evidence, rushed writing, incomplete research, or a binding plan the family cannot evaluate." },
      { heading: "Rates conceal composition", body: "Early pools may include recruited athletes and other institutionally prioritized applicants. Aggregate early acceptance rates do not provide an individual probability or prove that applying early caused the difference." },
    ],
    mistakes: ["Treating early application as a universal admissions boost.", "Using binding ED without a financial plan.", "Ignoring restrictions across institutions."],
    consultantPrompts: ["Is the application ready now?", "Can the family accept the binding financial uncertainty?"],
    studentFacingExplanation: "An early plan is useful only when the college fits, the application is ready, the rules are understood, and the financial commitment is responsible.",
    knowledgeCheck: { question: "Why can raw early admit rates mislead?", options: ["They are always false", "The pool includes different applicant groups and institutional priorities", "Early applications are never read"], correctIndex: 1, explanation: "Pool composition and institutional priorities limit individual inference." },
    relatedTools: ["Early-application decision worksheet", "Policy watch"],
  }),
  makeLesson({
    module: 11,
    slug: "recommendations",
    title: "Recommendations",
    summary: "Help students choose and support recommenders without scripting their words.",
    learningObjectives: ["Choose recommenders based on observation and relevance.", "Build an ethical information packet.", "Explain timing and FERPA waiver basics."],
    sections: [
      { heading: "Choose for evidence", body: "A useful recommender has observed the student’s learning, response to difficulty, participation, and character. The most prestigious teacher or highest grade is not automatically the strongest choice." },
      { heading: "Support without scripting", body: "Provide deadlines, a résumé or activity context when requested, relevant reflections, and concise reminders of real work. Students and parents should not draft the recommendation or prescribe praise." },
      { heading: "Process matters", body: "Ask respectfully and early, follow school procedures, waive access only after understanding the FERPA choice, send reminders sparingly, and thank the recommender regardless of the outcome." },
    ],
    mistakes: ["Selecting only by grade or title.", "Sending parent-written recommendation language.", "Waiting until deadlines are imminent."],
    consultantPrompts: ["Who has seen the student think and respond to difficulty?", "What real examples could help a recommender remember the student’s work?"],
    studentFacingExplanation: "Choose people who know how you learn and contribute. You can provide context and reminders, but their letter must be their own independent account.",
    knowledgeCheck: { question: "What makes a recommender useful?", options: ["Prestige", "Specific firsthand observation of learning and contribution", "A willingness to use the student’s draft"], correctIndex: 1, explanation: "Credible firsthand detail is the foundation of a useful recommendation." },
    relatedTools: ["Recommendation brag-sheet guide", "Glossary: FERPA waiver"],
  }),
  makeLesson({
    module: 12,
    slug: "essays-and-voice",
    title: "Essays and application voice",
    summary: "Support reflection and revision while protecting student authorship and a believable voice.",
    learningObjectives: ["Define the purpose of major essay types.", "Maintain student ownership through revision.", "Set ethical boundaries for consultant and AI assistance."],
    sections: [
      { heading: "Different writing does different work", body: "The personal statement offers a lens on the student; supplements test specific research, academic direction, community thinking, and contribution. Activity descriptions and Additional Information should clarify rather than repeat." },
      { heading: "Revision preserves ownership", body: "Consultants may ask questions, identify confusion, point to repetition, and teach revision. They should not supply experiences, rewrite the piece into an adult voice, or turn the essay into a formula." },
      { heading: "AI is a boundary issue", body: "A student may use permitted tools for organization or feedback only within school and application rules. Generated prose that replaces student thinking, voice, or authorship is not acceptable; policies and disclosure expectations must be checked." },
    ],
    mistakes: ["Using a ‘perfect Ivy essay’ formula.", "Editing until the student no longer sounds like themselves.", "Repeating the activity list instead of adding insight."],
    consultantPrompts: ["What question helps the student think rather than giving them a sentence?", "Could the student explain and defend every word as their own?"],
    studentFacingExplanation: "Your essays should sound like you and reflect choices you actually made. I can help you see where a reader is confused and ask questions that support your revision; I will not write the essay for you.",
    knowledgeCheck: { question: "Which feedback protects authorship?", options: ["Replacing a paragraph with consultant prose", "Naming the unclear point and asking the student to explain it", "Giving a universal opening formula"], correctIndex: 1, explanation: "Question-led feedback returns the intellectual work to the student." },
    relatedTools: ["Essay inventory", "Application architecture map", "Ethics"],
  }),
  makeLesson({
    module: 13,
    slug: "financial-aid-and-affordability",
    title: "Financial aid and affordability",
    summary: "Make net cost and debt part of fit from the beginning.",
    learningObjectives: ["Distinguish sticker price, net price, need-based aid, and merit aid.", "Use net price calculators and compare offers.", "Identify ED and deadline risks."],
    sections: [
      { heading: "Price is individualized", body: "Sticker price is the published cost; net price estimates what a family may pay after grants and scholarships. Need-based and merit aid follow different institutional rules, and not every college offers both." },
      { heading: "Use official planning tools", body: "Run each institution’s net price calculator with accurate family information, note assumptions, and revisit when circumstances change. Track FAFSA, CSS Profile, institutional forms, and aid deadlines separately from admission deadlines." },
      { heading: "Compare the full commitment", body: "Compare grants, scholarships, loans, work expectations, renewal terms, travel, health insurance, and likely annual change. Binding ED deserves particular caution when a family needs to compare offers." },
    ],
    mistakes: ["Waiting until spring to discuss affordability.", "Treating a loan as equivalent to a grant.", "Assuming a binding early plan is safe without a realistic estimate."],
    consultantPrompts: ["What is the family’s workable annual range?", "Which assumptions drive this net price estimate?"],
    studentFacingExplanation: "Affordability is part of fit. We will estimate costs early, track required forms, and compare the full four-year commitment. This tool does not provide legal, tax, or individualized financial advice.",
    knowledgeCheck: { question: "What does net price aim to estimate?", options: ["Published cost before aid", "Cost after grants and scholarships for a particular family profile", "Guaranteed final bill"], correctIndex: 1, explanation: "A calculator estimate is personalized but still not a guarantee of the final offer." },
    relatedTools: ["Financial-fit checklist", "Early-application decision worksheet"],
  }),
  makeLesson({
    module: 14,
    slug: "interviews-updates-waitlists-decisions",
    title: "Interviews, updates, waitlists, and decisions",
    summary: "Guide post-submission communication and final choices without overclaiming influence.",
    learningObjectives: ["Prepare for interviews without scripting.", "Evaluate meaningful updates and continued-interest letters.", "Compare admission and aid decisions responsibly."],
    sections: [
      { heading: "Prepare for conversation", body: "Students should be ready to discuss interests, questions, and fit in their own words. Practice reflection and listening rather than memorizing polished answers. Interview availability and evaluative weight vary by institution." },
      { heading: "Communicate only when useful", body: "A meaningful update adds new, material information. A continued-interest letter should follow institutional instructions, remain concise, and avoid manufactured claims or repeated contact." },
      { heading: "Decisions require care", body: "Compare academic opportunity, community, support, cost, aid terms, and student preferences. Maintain coursework, meet enrollment deadlines, withdraw other applications after committing, and treat waitlists as uncertain." },
    ],
    mistakes: ["Over-rehearsing an interview into a script.", "Sending trivial or repeated updates.", "Ignoring financial-aid differences during decision comparison."],
    consultantPrompts: ["Is this update new and material?", "What conditions matter for the student’s next four years?"],
    studentFacingExplanation: "After submission, follow each college’s instructions, communicate only when you have useful new information, and compare decisions across learning, community, support, and cost.",
    knowledgeCheck: { question: "What makes an application update appropriate?", options: ["Frequent contact", "New, material information sent according to instructions", "A restatement of the application"], correctIndex: 1, explanation: "Updates should add relevant evidence and respect the institution’s process." },
    relatedTools: ["Deferral response checklist", "Waitlist planning guide", "Decision-comparison worksheet"],
  }),
  makeLesson({
    module: 15,
    slug: "working-with-families",
    title: "Working with families",
    summary: "Structure communication so the student retains ownership while families address real constraints.",
    learningObjectives: ["Set consent, confidentiality, and communication boundaries.", "Address prestige pressure and disagreement.", "Recognize when to refer to another professional."],
    sections: [
      { heading: "Name the decision roles", body: "The student should lead educational and application choices. Parents appropriately set financial limits and share relevant family context. The consultant structures conversation and prevents either party from using the process to silence the other." },
      { heading: "Make conflict discussable", body: "Separate stated positions from underlying concerns: security, status, distance, cost, culture, or fear. Use agenda time for each perspective and return to shared criteria rather than winning an argument." },
      { heading: "Know the referral boundary", body: "Refer mental-health concerns, legal questions, complex financial or tax issues, disability accommodation decisions, and school-specific academic interventions to qualified professionals while continuing appropriate counseling support." },
    ],
    mistakes: ["Letting parent communication bypass the student by default.", "Treating anxiety as a motivation problem.", "Giving legal, tax, or mental-health advice outside scope."],
    consultantPrompts: ["What boundary protects student ownership?", "Which concern requires a school or licensed professional?"],
    studentFacingExplanation: "Your family may have important financial and practical constraints, and your voice must remain central. We will make decision roles and communication boundaries clear.",
    knowledgeCheck: { question: "Which issue should be referred?", options: ["Creating a meeting agenda", "Individualized legal or mental-health advice", "Explaining an application deadline"], correctIndex: 1, explanation: "Consultants should remain within competence and connect families to qualified professionals." },
    relatedTools: ["Parent intake questionnaire", "Meeting agenda template", "Consult session"],
  }),
  makeLesson({
    module: 16,
    slug: "consulting-operations",
    title: "Consulting operations",
    summary: "Build reliable intake, documentation, follow-up, privacy, policy review, and error-handling practices.",
    learningObjectives: ["Create a repeatable meeting and follow-up system.", "Apply privacy and record-retention boundaries.", "Maintain current source-governed content."],
    sections: [
      { heading: "A repeatable meeting cycle", body: "Prepare an objective and agenda, document concise evidence and decisions, assign owners and dates, send a clear summary, and review outstanding work before the next meeting." },
      { heading: "Minimum necessary records", body: "Collect only information needed for the counseling purpose, distinguish observation from interpretation, protect access, define retention, and avoid placing sensitive student details in analytics or casual tools." },
      { heading: "Policy and error discipline", body: "Verify school policies against official sources each cycle, record review dates, correct errors openly, and avoid marketing claims that imply guaranteed outcomes. Archived information must never silently appear current." },
    ],
    mistakes: ["Keeping unstructured notes without decisions or owners.", "Collecting more sensitive data than the work requires.", "Reusing old policy guidance without a review record."],
    consultantPrompts: ["What is the minimum information this meeting requires?", "Which claims are stable guidance and which need a current source?"],
    studentFacingExplanation: "I will keep the process organized, collect only information needed for the work, document decisions, and verify changing college policies before relying on them.",
    knowledgeCheck: { question: "What should happen when a policy cycle changes?", options: ["Carry the old rule forward", "Archive the old record and verify a new official source", "Remove all dates"], correctIndex: 1, explanation: "Cycle-specific claims require a new verification record." },
    relatedTools: ["Meeting summary template", "Annual policy-review checklist", "Settings"],
  }),
];

export const lessons = validateCollection(lessonSchema, rawLessons).sort((a, b) => a.module - b.module);

export function getLesson(slug: string) {
  return lessons.find((lesson) => lesson.slug === slug);
}
