import { schoolSchema, validateCollection, type School } from "./schema";

const cycle = "2026–27";
const verified = "2026-07-10";

const rawSchools: School[] = [
  {
    id: "harvard", slug: "harvard", name: "Harvard University", shortName: "Harvard", location: "Cambridge, Massachusetts",
    undergraduatePhilosophy: "A broad liberal arts and sciences education within a large research university, supported by residential communities and extensive academic resources.",
    curriculumModel: "General Education, distribution, language, writing, and concentration requirements leave substantial breadth within a structured degree.",
    campusContext: "Urban-adjacent Cambridge and Boston; a large research ecosystem organized around a residential undergraduate college.",
    undergraduateStructure: "Most undergraduates enter Harvard College and later declare a concentration rather than applying to a professional undergraduate school.",
    applicationRoundOverview: "Harvard offers nonbinding Restrictive Early Action and Regular Decision. The restrictions and exact dates are cycle-bound; read the current policy record before planning.",
    financialAidOverview: "Harvard describes undergraduate aid as need-based. Use its official estimator and current aid pages to review eligibility, required forms, deadlines, and the family’s estimated net price; institutional policy must be rechecked each cycle.",
    usefulComparisonSchools: ["Yale for residential liberal arts exploration", "Princeton for undergraduate-centered independent work", "Stanford for broad research-university choice", "Duke for residential research-university breadth"],
    distinctiveFeatures: ["Exceptional breadth across a research university", "House-based residential community", "Cross-registration and regional academic access", "Concentration chosen after exploration"],
    strongFitTraits: ["Broad intellectual curiosity", "Initiative in navigating abundant resources", "Academic depth paired with contribution", "Comfort in a large, decentralized ecosystem"],
    possibleMismatchTraits: ["Wants a prescribed professional curriculum immediately", "Is attracted only by the name", "Prefers a small institution with few choices"],
    studentQuestions: ["Which Harvard concentration and courses have I actually investigated?", "How would I use the House system?", "Do abundant choices energize me or create friction?"],
    commonMisconceptions: ["Harvard has a single admissions formula or a profile that guarantees admission."],
    comparisonNotes: { flexibility: "Broad choice within general education and concentration requirements.", commonCurriculum: "No Columbia-style common Core; students complete requirement categories.", undergraduateFocus: "Harvard College sits inside a very large research university.", researchIntensity: "Extensive research ecosystem across the university; undergraduates must navigate proactively.", independentWork: "Varies by concentration; not a universal Princeton-style thesis culture.", academicExploration: "Broad exploration before and within a concentration.", urbanity: "Cambridge with immediate access to Boston.", scale: "Resource-rich and institutionally large.", residential: "House system organizes much of undergraduate life.", schoolChoice: "Broad entry to Harvard College.", preprofessional: "Strong pathways exist, but the degree is liberal arts and sciences.", facultyAccess: "Significant opportunity; students must navigate proactively.", community: "Residential houses within a large ecosystem." },
    majorConsiderations: "Students usually enter the college broadly and choose a concentration later; investigate prerequisites, departmental culture, advising, and whether the desired field is an undergraduate concentration.",
    supplementResearchPrompts: ["Which academic resource would change how you pursue an existing question?", "How would you contribute to a House, classroom, or campus community?"],
    policyIds: ["harvard-testing-2026-27", "harvard-early-2026-27"],
    officialSources: [{ title: "Harvard College academics", url: "https://college.harvard.edu/academics" }, { title: "Harvard College admissions", url: "https://college.harvard.edu/admissions" }, { title: "Harvard College financial aid", url: "https://college.harvard.edu/financial-aid" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "current",
    consultantSummary: "Test whether the student is drawn to Harvard’s breadth, House community, and self-directed use of a huge research ecosystem—not merely its status.",
    studentSummary: "Harvard offers broad study and exceptional resources. Fit depends on how you would use that breadth and participate in a residential academic community.",
  },
  {
    id: "yale", slug: "yale", name: "Yale University", shortName: "Yale", location: "New Haven, Connecticut",
    undergraduatePhilosophy: "Exploration-oriented liberal arts education with a strong residential-college community and close attention to discussion, writing, arts, sciences, and campus contribution.",
    curriculumModel: "Distributional requirements across skills and subject areas support exploration before and alongside the major.",
    campusContext: "A residential university in New Haven, with undergraduates rooted in fourteen residential colleges.",
    undergraduateStructure: "Yale College provides the undergraduate liberal arts experience; students generally select a major after entering.",
    applicationRoundOverview: "Yale offers nonbinding Single-Choice Early Action and Regular Decision. Current restrictions, exceptions, and exact dates must be verified for the student’s cycle.",
    financialAidOverview: "Yale describes undergraduate institutional aid as need-based. Use Yale’s official aid tools and current pages to review forms, deadlines, eligibility, and estimated net price.",
    usefulComparisonSchools: ["Brown for greater curricular freedom", "Princeton for required independent work", "Amherst for a smaller open-curriculum college", "Duke for residential research-university breadth"],
    distinctiveFeatures: ["Residential colleges from entry", "Strong arts and humanities alongside sciences", "Exploratory liberal arts structure", "Seminar and discussion culture"],
    strongFitTraits: ["Enjoys close residential community", "Values discussion, writing, arts, or public service", "Contributes actively to peers", "Wants exploration before narrowing"],
    possibleMismatchTraits: ["Wants a primarily preprofessional environment", "Dislikes a strong residential identity", "Uses only generic prestige reasoning"],
    studentQuestions: ["What would I contribute to a residential college?", "How would Yale’s distribution system shape exploration?", "Which academic and cultural communities feel specific to my interests?"],
    commonMisconceptions: ["Yale can be reduced to a humanities identity; its sciences and research are substantial."],
    comparisonNotes: { flexibility: "Exploration within distribution requirements.", commonCurriculum: "Shared distribution categories, not a fixed common sequence.", undergraduateFocus: "Yale College is central within a research university.", researchIntensity: "Research-university access paired with a strong undergraduate liberal arts identity.", independentWork: "Senior requirements vary by major.", academicExploration: "Exploration is supported through distribution requirements and later major choice.", urbanity: "Small city setting with a concentrated campus.", scale: "Mid-sized university with intimate residential units.", residential: "Fourteen residential colleges shape identity and support.", schoolChoice: "Broad entry to Yale College.", preprofessional: "Liberal arts orientation with strong career pathways.", facultyAccess: "Seminars and undergraduate teaching are prominent, with variation by field.", community: "Residential, arts-rich, and participation-oriented." },
    majorConsiderations: "Students enter Yale College rather than a separate undergraduate professional school; examine major requirements, senior expectations, and departmental course access.",
    supplementResearchPrompts: ["Which residential and academic communities would you join?", "What kind of classroom conversation helps you think?"],
    policyIds: ["yale-testing-2026-27", "yale-early-2026-27"],
    officialSources: [{ title: "Yale College academics", url: "https://yalecollege.yale.edu/academics" }, { title: "Yale undergraduate admissions", url: "https://admissions.yale.edu/" }, { title: "Yale undergraduate financial aid", url: "https://finaid.yale.edu/" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "current",
    consultantSummary: "Probe the student’s interest in exploratory liberal arts study, residential contribution, and discussion-rich community rather than relying on a broad ‘Yale culture’ claim.",
    studentSummary: "Yale combines broad exploration with a close residential-college experience. It may fit students who want intellectual and community participation to reinforce each other.",
  },
  {
    id: "princeton", slug: "princeton", name: "Princeton University", shortName: "Princeton", location: "Princeton, New Jersey",
    undergraduatePhilosophy: "An undergraduate-centered research education emphasizing close mentorship, independent inquiry, and sustained scholarly work.",
    curriculumModel: "A liberal arts curriculum with general requirements and strong departmental pathways, culminating in significant independent work.",
    campusContext: "A residential campus in a small town with access to major East Coast cities by rail.",
    undergraduateStructure: "Students pursue the A.B. or B.S.E.; engineering choice shapes requirements, and all students engage in department-specific independent work.",
    applicationRoundOverview: "Princeton offers nonbinding Single-Choice Early Action and Regular Decision. Current exceptions and exact dates are cycle-specific and should be read directly.",
    financialAidOverview: "Princeton describes undergraduate aid as need-based and grant-focused. Use the official aid estimator and current policy pages to evaluate family contribution, required documents, and deadlines.",
    usefulComparisonSchools: ["Yale for residential exploration", "Williams for a smaller undergraduate-centered setting", "MIT for technically intensive undergraduate research", "Rice for residential colleges and research access"],
    distinctiveFeatures: ["Junior independent work", "Senior thesis or substantial independent project traditions", "Strong undergraduate teaching emphasis", "Residential colleges and close faculty mentorship"],
    strongFitTraits: ["Enjoys sustained independent inquiry", "Wants close mentorship", "Values depth and rigorous writing or research", "Comfortable in a residential small-town setting"],
    possibleMismatchTraits: ["Strongly dislikes extended independent work", "Requires a dense urban professional environment", "Is interested only in prestige"],
    studentQuestions: ["What question could I sustain over months?", "How do I respond when independent work becomes difficult?", "Would the campus setting support how I want to live?"],
    commonMisconceptions: ["Independent work is only for humanities students; its form varies across departments and engineering."],
    comparisonNotes: { flexibility: "Structured breadth with major-specific depth.", commonCurriculum: "General requirements rather than a single shared Core.", undergraduateFocus: "Distinctive institutional emphasis on undergraduates.", researchIntensity: "Research is coupled to required undergraduate independent work.", independentWork: "A defining feature through junior work and senior requirements.", academicExploration: "Exploration leads toward sustained departmental depth.", urbanity: "Small-town residential campus.", scale: "Compact undergraduate population within a research university.", residential: "Residential colleges support early undergraduate life.", schoolChoice: "A.B. or B.S.E. pathways shape requirements.", preprofessional: "Less preprofessional in structure; strong outcomes and applied research.", facultyAccess: "Close mentorship is central to the model.", community: "Academic, residential, and campus-centered." },
    majorConsiderations: "A.B. and B.S.E. paths carry different requirements. Students should investigate departmental independent-work expectations rather than assuming one universal thesis form.",
    supplementResearchPrompts: ["Which independent question could Princeton help you pursue?", "How would you use faculty mentorship and the residential setting?"],
    policyIds: ["princeton-testing-2026-27", "princeton-early-2026-27"],
    officialSources: [{ title: "Princeton undergraduate academics", url: "https://www.princeton.edu/academics/undergraduate" }, { title: "Princeton admission", url: "https://admission.princeton.edu/" }, { title: "Princeton cost and aid", url: "https://admission.princeton.edu/cost-aid" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "current",
    consultantSummary: "The fit question is whether the student wants sustained independent scholarly work and close mentorship in a residential, undergraduate-centered setting.",
    studentSummary: "Princeton asks undergraduates to develop depth through independent work and mentorship. It may fit if you want to pursue a question for a long time, not just sample many options.",
  },
  {
    id: "columbia", slug: "columbia", name: "Columbia University", shortName: "Columbia", location: "New York, New York",
    undergraduatePhilosophy: "A shared intellectual foundation through the Core Curriculum, pursued within a research university that treats New York City as an academic and civic setting.",
    curriculumModel: "The Core Curriculum requires sustained common study in literature, philosophy, arts, music, science, writing, and contemporary civilization, alongside a major.",
    campusContext: "A compact campus in Morningside Heights embedded in New York City.",
    undergraduateStructure: "Applicants choose Columbia College or Columbia Engineering; the school choice changes curriculum and degree requirements.",
    applicationRoundOverview: "Columbia offers binding Early Decision and Regular Decision. Review the current agreement, financial considerations, exact dates, and school-specific requirements before choosing a round.",
    financialAidOverview: "Columbia describes institutional undergraduate aid for College and Engineering through a need-based process. Use the official estimator and current aid office requirements for forms, deadlines, eligibility, and net-price planning.",
    usefulComparisonSchools: ["University of Chicago for a structured common curriculum", "Brown for the opposite curricular model", "New York University for a less campus-contained urban experience", "Georgetown for urban academics and public-service access"],
    distinctiveFeatures: ["Structured Core Curriculum", "Shared texts and seminar discussion", "New York City integrated into learning", "Distinct college and engineering pathways"],
    strongFitTraits: ["Values a common intellectual foundation", "Enjoys intensive reading and discussion", "Is energized by urban life", "Can explain how the Core supports their goals"],
    possibleMismatchTraits: ["Seeks maximum curricular freedom", "Is uncomfortable with dense urban living", "Cannot explain why the Core appeals"],
    studentQuestions: ["Do I want required common texts and seminars?", "How would I use New York as an educational environment?", "Which undergraduate school matches my preparation and goals?"],
    commonMisconceptions: ["New York alone is not a sufficient explanation of fit; the Core and school-specific academic structure matter."],
    comparisonNotes: { flexibility: "Lower than Brown because of the substantial Core.", commonCurriculum: "The Core is a defining shared sequence.", undergraduateFocus: "Undergraduates study inside a major urban research university.", researchIntensity: "Extensive research access across a dense urban university ecosystem.", independentWork: "Varies by field; not institution-wide like Princeton.", academicExploration: "The Core creates common exploration while the major creates depth.", urbanity: "Dense New York City setting.", scale: "Compact campus within a large university and city.", residential: "Campus housing within an urban environment.", schoolChoice: "College or Engineering choice is consequential.", preprofessional: "Strong professional access through the city, within academic degrees.", facultyAccess: "Seminars are central in the Core; access varies elsewhere.", community: "Shared Core plus a highly urban student experience." },
    majorConsiderations: "College and Engineering have distinct requirements. Research both the Core or engineering core, major access, and how city opportunities interact with the academic schedule.",
    supplementResearchPrompts: ["Which part of the Core would challenge or extend your thinking?", "What would you do in New York that directly connects to your academic work?"],
    policyIds: ["columbia-testing-2026-27", "columbia-early-2026-27"],
    officialSources: [{ title: "Columbia College Core Curriculum", url: "https://www.college.columbia.edu/core/" }, { title: "Columbia undergraduate admissions", url: "https://undergrad.admissions.columbia.edu/" }, { title: "Columbia College and Engineering financial aid", url: "https://cc-seas.financialaid.columbia.edu/" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "current",
    consultantSummary: "Require evidence that the student wants both the Core’s shared intellectual obligations and New York’s density; city appeal alone is incomplete.",
    studentSummary: "Columbia combines a demanding shared Core with New York City. Fit depends on wanting both common intellectual study and an intensely urban environment.",
  },
  {
    id: "brown", slug: "brown", name: "Brown University", shortName: "Brown", location: "Providence, Rhode Island",
    undergraduatePhilosophy: "A student-directed education built around the Open Curriculum, interdisciplinary exploration, and responsibility for shaping an academic path.",
    curriculumModel: "The Open Curriculum removes general distribution requirements while requiring a concentration and evidence that the student can use freedom intentionally.",
    campusContext: "A residential campus on College Hill in Providence, connected to the city and Rhode Island School of Design.",
    undergraduateStructure: "Most undergraduates enter the College broadly; specialized pathways and the Program in Liberal Medical Education have separate considerations.",
    applicationRoundOverview: "Brown offers binding Early Decision and Regular Decision. Review the current ED agreement, financial implications, exact dates, and program-specific requirements before planning.",
    financialAidOverview: "Brown describes institutional undergraduate aid through a need-based process. Use Brown’s official aid tools and current requirements to assess forms, deadlines, eligibility, and estimated net price.",
    usefulComparisonSchools: ["Columbia for a required shared Core", "Yale for exploration within distribution requirements", "Wesleyan for a smaller exploratory liberal arts setting", "University of Rochester for curricular flexibility in a research university"],
    distinctiveFeatures: ["Open Curriculum", "Student ownership of course planning", "Interdisciplinary study", "Brown–RISD academic and creative proximity"],
    strongFitTraits: ["Self-directed academic decision-making", "Can explain how freedom will be used", "Interdisciplinary interests", "Comfort with responsibility and exploration"],
    possibleMismatchTraits: ["Wants extensive prescribed requirements", "Assumes Brown is academically easier", "Dislikes owning academic planning"],
    studentQuestions: ["What would I build with curricular freedom?", "Which concentration or combination of fields has specific appeal?", "How do I make decisions when requirements do not choose for me?"],
    commonMisconceptions: ["The Open Curriculum does not mean no structure, standards, or accountability."],
    comparisonNotes: { flexibility: "Exceptionally high through the Open Curriculum.", commonCurriculum: "No general distribution curriculum.", undergraduateFocus: "The College is central within a research university.", researchIntensity: "Research-university access within a highly self-directed undergraduate model.", independentWork: "Self-direction is pervasive; capstone expectations vary.", academicExploration: "Students design exploration with few general requirements and significant advising responsibility.", urbanity: "Small-city Providence setting.", scale: "Mid-sized and residential.", residential: "Campus community integrated with Providence.", schoolChoice: "Broad entry to the College for most applicants.", preprofessional: "Student-directed liberal education with pathways to applied fields.", facultyAccess: "Open exploration can support cross-field mentorship.", community: "Collaborative, exploratory, and self-directed." },
    majorConsiderations: "Freedom increases the need to research prerequisites, concentration requirements, advising, sequencing, and how interdisciplinary interests will form a coherent education.",
    supplementResearchPrompts: ["Design a plausible academic path, then explain why Brown makes it possible.", "What responsibility comes with the freedom you want?"],
    policyIds: ["brown-testing-2026-27", "brown-early-2026-27"],
    officialSources: [{ title: "Brown Open Curriculum", url: "https://college.brown.edu/design-your-education/explore-open-curriculum" }, { title: "Brown undergraduate admission", url: "https://admission.brown.edu/" }, { title: "Brown financial aid", url: "https://finaid.brown.edu/" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "current",
    consultantSummary: "Ask the student to demonstrate how they make academic choices and what they would build with freedom; ‘no requirements’ is not an adequate fit argument.",
    studentSummary: "Brown gives students unusual curricular freedom and expects them to use it responsibly. It may fit if you can design, explain, and sustain your own academic path.",
  },
  {
    id: "penn", slug: "penn", name: "University of Pennsylvania", shortName: "Penn", location: "Philadelphia, Pennsylvania",
    undergraduatePhilosophy: "An interdisciplinary university with strong professional and applied orientation across four undergraduate schools.",
    curriculumModel: "School-specific curricula in Arts and Sciences, Engineering, Nursing, and Wharton, with substantial opportunities for cross-school study.",
    campusContext: "A contiguous urban campus in West Philadelphia with strong civic, clinical, research, and professional connections.",
    undergraduateStructure: "Applicants select one of four undergraduate schools; coordinated dual-degree and specialized programs have distinct expectations.",
    applicationRoundOverview: "Penn offers binding Early Decision and Regular Decision. The agreement and undergraduate-school application requirements are consequential; exact current-cycle dates require verification.",
    financialAidOverview: "Penn describes undergraduate institutional aid through a need-based process. Use Student Registration and Financial Services resources to review eligibility, documents, deadlines, and net-price estimates; recheck the current cycle.",
    usefulComparisonSchools: ["Duke for interdisciplinary professional access", "Northwestern for multi-school flexibility", "Georgetown for urban professional and public-service study", "Carnegie Mellon for program-specific applied education"],
    distinctiveFeatures: ["Four undergraduate schools", "Cross-school and interdisciplinary pathways", "Strong practical application", "Urban clinical, business, engineering, and civic context"],
    strongFitTraits: ["Has a comparatively clear academic direction", "Connects theory to practical outcomes", "Can explain a specific undergraduate school", "Values interdisciplinary work"],
    possibleMismatchTraits: ["Has not researched the undergraduate school", "Uses only generic business or networking language", "Prefers a less professionally oriented setting"],
    studentQuestions: ["Why this undergraduate school rather than Penn generally?", "Which cross-school opportunity is academically necessary for my goals?", "How do I want practice and theory to interact?"],
    commonMisconceptions: ["Penn is not synonymous with Wharton; each undergraduate school has a distinct academic identity."],
    comparisonNotes: { flexibility: "Varies substantially by undergraduate school.", commonCurriculum: "School-specific requirements rather than one university-wide Core.", undergraduateFocus: "Undergraduate programs sit inside a large professional research university.", researchIntensity: "Research is extensive and often connected to applied, clinical, technical, or professional settings.", independentWork: "Available but not the universal organizing principle.", academicExploration: "Exploration often crosses schools but begins from a consequential home-school curriculum.", urbanity: "Integrated Philadelphia campus.", scale: "Large, interdisciplinary university.", residential: "Campus-centered life in an urban setting.", schoolChoice: "Four-school application choice is central.", preprofessional: "The strongest explicit preprofessional orientation among the eight.", facultyAccess: "Varies by school; interdisciplinary access is a major opportunity.", community: "Energetic, applied, cross-school, and urban." },
    majorConsiderations: "The applicant must match preparation and goals to a specific school. Specialized and coordinated programs require far more than a generic interest in two subjects.",
    supplementResearchPrompts: ["Why does the chosen undergraduate school fit the way you want to learn?", "Which cross-school connection advances a real question rather than adding a label?"],
    policyIds: ["penn-testing-2026-27", "penn-early-2026-27"],
    officialSources: [{ title: "Penn undergraduate academics", url: "https://www.upenn.edu/academics/undergraduate" }, { title: "Penn admissions", url: "https://admissions.upenn.edu/" }, { title: "Penn undergraduate financial aid", url: "https://srfs.upenn.edu/financial-aid" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "verification-needed",
    consultantSummary: "School-specific fit is the key diagnostic. The student should connect preparation and goals to Arts and Sciences, Engineering, Nursing, or Wharton—not to Penn as a generic brand.",
    studentSummary: "Penn’s four undergraduate schools combine focused study with cross-school options. Fit starts with knowing which school matches your goals and why applied, interdisciplinary work matters to you.",
  },
  {
    id: "dartmouth", slug: "dartmouth", name: "Dartmouth College", shortName: "Dartmouth", location: "Hanover, New Hampshire",
    undergraduatePhilosophy: "A close undergraduate-centered liberal arts community with research access, faculty interaction, experiential learning, and a flexible academic calendar.",
    curriculumModel: "Liberal arts distribution and major requirements operate across the year-round quarter-based D-Plan.",
    campusContext: "A rural small-town residential campus with outdoor, regional, and close-community implications.",
    undergraduateStructure: "Students enter the undergraduate college broadly; professional graduate schools coexist but do not divide undergraduate admission by school.",
    applicationRoundOverview: "Dartmouth offers binding Early Decision and Regular Decision. Review the current agreement, restrictions, financial provisions, and exact dates before choosing an early plan.",
    financialAidOverview: "Dartmouth describes undergraduate aid through a need-based process. Use its official cost tools and current aid instructions to evaluate eligibility, documents, deadlines, and net price.",
    usefulComparisonSchools: ["Williams for a smaller undergraduate-centered setting", "Middlebury for a rural residential liberal arts environment", "Bowdoin for close community and undergraduate focus", "Notre Dame for a strong residential identity in a research university"],
    distinctiveFeatures: ["D-Plan flexible calendar", "Small undergraduate-centered environment", "Strong faculty interaction", "Rural residential community and experiential learning"],
    strongFitTraits: ["Wants a close campus community", "Values smaller classes and faculty access", "Can use schedule flexibility intentionally", "Is comfortable outside a major city"],
    possibleMismatchTraits: ["Requires a major city", "Wants anonymity in a very large university", "Has not considered location or calendar"],
    studentQuestions: ["How would I use the D-Plan deliberately?", "What does a rural residential setting make possible and difficult?", "Do I want a community where participation is highly visible?"],
    commonMisconceptions: ["The D-Plan is not simply extra vacation; sequencing, housing, internships, and community rhythms require planning."],
    comparisonNotes: { flexibility: "D-Plan creates scheduling flexibility within liberal arts requirements.", commonCurriculum: "Distribution and world-culture requirements, not a fixed Core.", undergraduateFocus: "A defining strength.", researchIntensity: "Research access is substantial for the size and often connected to close faculty interaction.", independentWork: "Research and thesis options are strong but field-specific.", academicExploration: "Liberal arts breadth is shaped by a flexible year-round calendar.", urbanity: "Rural small-town setting.", scale: "Smaller undergraduate community.", residential: "Highly campus-centered.", schoolChoice: "Broad undergraduate entry.", preprofessional: "Liberal arts core with strong experiential and career pathways.", facultyAccess: "A prominent part of the undergraduate model.", community: "Close, active, and place-based." },
    majorConsiderations: "Investigate quarter sequencing, off-campus terms, departmental offerings, and whether the D-Plan supports or complicates laboratories, internships, athletics, or other commitments.",
    supplementResearchPrompts: ["Show how you would use one D-Plan sequence intentionally.", "What contribution would you make in a close residential community?"],
    policyIds: ["dartmouth-testing-2026-27", "dartmouth-early-2026-27"],
    officialSources: [{ title: "Dartmouth undergraduate education", url: "https://home.dartmouth.edu/education/undergraduate-arts-sciences" }, { title: "Dartmouth admissions", url: "https://admissions.dartmouth.edu/" }, { title: "Dartmouth financial aid", url: "https://financialaid.dartmouth.edu/" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "current",
    consultantSummary: "Location, scale, community visibility, faculty access, and D-Plan use should all be tested. A student who needs a city should not treat Hanover as incidental.",
    studentSummary: "Dartmouth offers a close, undergraduate-focused community and a flexible calendar in a rural setting. Fit depends on wanting the place and community as much as the academic opportunities.",
  },
  {
    id: "cornell", slug: "cornell", name: "Cornell University", shortName: "Cornell", location: "Ithaca, New York",
    undergraduatePhilosophy: "A broad university spanning liberal, scientific, technical, professional, and applied study, shaped by land-grant and public-service traditions.",
    curriculumModel: "Requirements are defined by the selected undergraduate college or school; academic fit is unusually specific at application.",
    campusContext: "A large residential campus in Ithaca with a college-town setting, substantial natural landscape, and diverse academic communities.",
    undergraduateStructure: "Applicants choose one of several undergraduate colleges or schools, including contract colleges with distinct missions and requirements.",
    applicationRoundOverview: "Cornell offers binding Early Decision and Regular Decision. Applicants choose a specific undergraduate college; review the current agreement, supporting-material dates, and college requirements.",
    financialAidOverview: "Cornell’s undergraduate aid process includes need-based institutional aid and college-specific cost considerations. Use the official estimator and current financial-aid pages to review eligibility, forms, deadlines, and net price.",
    usefulComparisonSchools: ["University of Michigan for broad public research-university programs", "Carnegie Mellon for specialized technical and applied study", "Northwestern for multi-school interdisciplinary options", "UC Berkeley for large-scale applied and theoretical research"],
    distinctiveFeatures: ["Wide range of specialized undergraduate colleges", "Applied and theoretical study", "Land-grant public-service mission", "Large academically diverse campus"],
    strongFitTraits: ["Has a defined academic direction", "Values applied and theoretical work", "Can explain a specific college or school", "Is comfortable in a larger university"],
    possibleMismatchTraits: ["Treats undergraduate colleges as interchangeable", "Has not researched program-specific expectations", "Is attracted only by the Ivy label"],
    studentQuestions: ["Why this Cornell college and program?", "Which mission or curriculum requirement supports my goals?", "Do I want a large, decentralized university in Ithaca?"],
    commonMisconceptions: ["There is no single interchangeable Cornell undergraduate experience; college structure matters from application onward."],
    comparisonNotes: { flexibility: "Highly dependent on college and program.", commonCurriculum: "No single university-wide undergraduate Core.", undergraduateFocus: "Strong undergraduate options inside a large complex university.", researchIntensity: "Extensive research across applied, technical, professional, and liberal fields.", independentWork: "Varies by college and major.", academicExploration: "Exploration is bounded by college-specific missions, requirements, and transfer rules.", urbanity: "College-town and natural setting.", scale: "Largest and most academically diverse Ivy undergraduate ecosystem.", residential: "Large residential campus with college-specific communities.", schoolChoice: "College-specific application is essential.", preprofessional: "Extensive applied and professional undergraduate study.", facultyAccess: "Strong research access; navigation varies with scale.", community: "Diverse, decentralized, and program-specific." },
    majorConsiderations: "Requirements, transfer rules, portfolio expectations, and academic missions differ by college. A general Cornell statement is not adequate research.",
    supplementResearchPrompts: ["Which college-specific curriculum or mission matches your record?", "How would you use Cornell’s applied and land-grant traditions?"],
    policyIds: ["cornell-testing-2026-27", "cornell-early-2026-27"],
    officialSources: [{ title: "Cornell undergraduate colleges and schools", url: "https://www.cornell.edu/academics/colleges.cfm" }, { title: "Cornell admissions", url: "https://admissions.cornell.edu/" }, { title: "Cornell financial aid", url: "https://finaid.cornell.edu/" }],
    applicationCycle: cycle, lastVerifiedAt: verified, verificationStatus: "current",
    consultantSummary: "College-specific fit is nonnegotiable. Require precise research into mission, curriculum, and preparation rather than a generic Cornell narrative.",
    studentSummary: "Cornell offers the broadest range of specialized undergraduate programs in the Ivy League. Fit depends on choosing and understanding the specific college that matches your direction.",
  },
];

export const schools = validateCollection(schoolSchema, rawSchools);

export function getSchool(slug: string) {
  return schools.find((school) => school.slug === slug);
}
