import { toolkitSchema, validateCollection, type ToolkitItem } from "./schema";

type Seed = [id: string, title: string, purpose: string, whenToUse: string, fields: string[], mistakes: string[]];

const seeds: Seed[] = [
  ["student-intake", "Student intake questionnaire", "Understand the student’s goals, context, responsibilities, learning preferences, and concerns without reducing them to credentials.", "Before or during the first student meeting.", ["Student or case label", "Grade and school context", "Goals for college", "Learning interests", "Responsibilities and constraints", "Support needs", "Questions for the consultant"], ["Requesting a full legal name when a label will do", "Beginning with college names instead of student goals"]],
  ["parent-intake", "Parent intake questionnaire", "Clarify family goals, financial parameters, decision roles, and communication expectations.", "During a separate or shared initial parent conversation.", ["Family goals", "Workable annual range", "Net price calculator status", "Decision roles", "Communication expectations", "Student responsibilities", "Confidentiality questions"], ["Avoiding the financial conversation", "Letting the intake displace the student’s voice"]],
  ["transcript-review", "Transcript-review checklist", "Interpret preparation and trends in the context of the school’s curriculum.", "At initial academic review and after each term.", ["Grading scale", "School profile reviewed", "Core subjects", "Rigor relative to availability", "Grade trends", "Gaps or repeats", "Senior-year plan"], ["Comparing weighted GPAs across schools", "Ignoring course availability"]],
  ["course-rigor", "Course-rigor review", "Plan appropriate academic challenge without creating unsustainable overload.", "Before course registration or schedule changes.", ["Available advanced courses", "Prerequisites", "Current workload", "Field preparation", "Support plan", "Wellbeing constraints", "Proposed sequence"], ["Maximizing advanced-course count", "Closing doors through an unexamined prerequisite gap"]],
  ["activity-inventory", "Activity inventory", "Document sustained engagement, responsibility, initiative, contribution, and reflection accurately.", "From grade 9 onward; formalize during grade 11.", ["Commitment", "Dates and hours", "Role", "Specific responsibilities", "Initiative", "Contribution", "Reflection", "Verifier or context"], ["Inflating hours or impact", "Omitting work and family care"]],
  ["intellectual-curiosity", "Intellectual-curiosity interview", "Surface questions and self-directed learning that matter to the student.", "During exploration, school research, or essay preparation.", ["Questions pursued", "Reading or making beyond class", "Difficult problem", "Connections across fields", "Changed mind", "Next question"], ["Manufacturing a project", "Equating curiosity with expensive access"]],
  ["summer-plan", "Summer planning worksheet", "Build a feasible plan across work, care, learning, contribution, projects, and rest.", "Between December and May for the coming summer.", ["Constraints", "Responsibilities", "Goals", "Options considered", "Cost", "Actual work involved", "Recovery time", "Decision"], ["Choosing by brand", "Planning away all rest"]],
  ["college-fit", "College-fit questionnaire", "Identify learning, community, support, place, and cost conditions that matter.", "Before list building and again before decisions.", ["Academic model", "Major access", "Campus scale", "Location", "Community", "Support", "Affordability", "Distance", "Accessibility", "Must-haves and tradeoffs"], ["Treating ranking as fit", "Ignoring cost or support"]],
  ["college-research", "College research worksheet", "Turn a college name into specific evidence and open questions.", "For every serious list candidate.", ["Curriculum", "Program access", "Class experience", "Research", "Community", "Support", "Housing", "Cost and aid", "Official sources", "Questions remaining"], ["Copying marketing language", "Researching only admission statistics"]],
  ["ivy-comparison", "Ivy comparison worksheet", "Compare educational models and student preferences without declaring a perfect match.", "When a student is considering two or three Ivy institutions.", ["Schools", "Curriculum model", "Undergraduate structure", "Setting", "Community", "Student preferences", "Mismatch indicators", "Questions to verify"], ["Treating all eight as interchangeable", "Using school colors or rank as the comparison"]],
  ["balanced-list", "Balanced college-list worksheet", "Create a list with high reach, reach, possible, likely, and financially likely options the student would attend.", "From spring of grade 11 through early fall of grade 12.", ["College", "Planning category", "Academic fit", "Personal fit", "Net price estimate", "Financial category", "Application plan", "Why the student would attend"], ["Calling an Ivy a target", "Including a likely the student would not attend"]],
  ["testing-plan", "Testing plan", "Choose a primary exam and bounded schedule using diagnostics and current policies.", "Grade 10 or 11, then revise as policies and results change.", ["SAT diagnostic", "ACT diagnostic", "Primary test", "Preparation method", "Official dates", "Policy checks", "Stop condition", "Accommodations or access"], ["Testing indefinitely", "Using one universal score target"]],
  ["recommendation-guide", "Recommendation brag-sheet guide", "Give recommenders relevant context without drafting their letter.", "Before the school’s recommendation request deadline.", ["Course and teacher", "Work remembered", "Response to challenge", "Contribution to class", "Academic direction", "Relevant responsibilities", "Deadline and procedure"], ["Writing praise for the teacher to copy", "Choosing only by grade"]],
  ["essay-inventory", "Essay inventory", "Map experiences, questions, values, and required prompts without forcing a formula.", "Before drafting the personal statement and supplements.", ["Experience or question", "Why it matters", "Change or tension", "Evidence", "Possible prompt", "Repetition risk", "Student voice check"], ["Searching for a ‘perfect Ivy topic’", "Repeating the activity list"]],
  ["application-map", "Application architecture map", "Coordinate the role of each application section so the whole record is accurate and nonrepetitive.", "After the list and prompt set are known.", ["Core application", "Activities", "Honors", "Personal statement", "Supplements", "Additional Information", "Recommendations", "Context covered", "Gaps and repetition"], ["Making every section tell the same story", "Using Additional Information as another essay"]],
  ["early-decision", "Early-application decision worksheet", "Evaluate readiness, fit, restrictions, and financial implications before choosing an early plan.", "Before committing to ED, EA, REA, SCEA, or rolling plans.", ["Institution and plan", "Binding status", "Restrictions", "Current official source", "Application readiness", "Fit evidence", "Net price estimate", "Family decision", "Backup plan"], ["Using raw early rates as an individual probability", "Binding without financial review"]],
  ["financial-fit", "Financial-fit checklist", "Make affordability and aid requirements part of college fit.", "During list building, before ED, and when comparing offers.", ["Published cost", "Net price calculator", "Family range", "Aid forms", "Deadlines", "Grant and loan mix", "Renewal terms", "Travel and other costs", "Four-year concern"], ["Treating loans as grants", "Waiting until admission to discuss cost"]],
  ["meeting-agenda", "Meeting agenda template", "Keep a consultation focused, shared, and time-bounded.", "Before every meeting.", ["Student or case label", "Date and meeting type", "Objective", "Agenda items", "Evidence to review", "Decisions needed", "Time allocation", "Closing recap"], ["Using a generic agenda for every meeting", "Ending without decisions or owners"]],
  ["meeting-summary", "Meeting summary template", "Record decisions, cautions, owners, and next actions in clear student-facing language.", "Immediately after each meeting.", ["Meeting objective", "What we reviewed", "Decisions", "Open questions", "Student actions", "Parent actions", "Consultant actions", "Dates", "Privacy note"], ["Recording unnecessary sensitive detail", "Listing tasks without owners"]],
  ["application-qc", "Application quality-control checklist", "Catch factual, ethical, technical, and submission errors before sending.", "At least 48 hours before every deadline.", ["Names and dates", "School and program", "Course entries", "Activities and hours", "Essay prompt match", "Student voice", "Recommendations", "Aid forms", "Policy verified", "Portal follow-up"], ["Editing at the submission deadline", "Assuming submission means materials are complete"]],
  ["deferral", "Deferral response checklist", "Respond to deferral instructions calmly while keeping other options active.", "After a deferral decision.", ["Official instructions", "Continued interest decision", "Material updates", "Midyear report", "Counselor coordination", "Other applications", "Contact limit", "Follow-up date"], ["Sending a long emotional appeal", "Neglecting other applications"]],
  ["waitlist", "Waitlist planning guide", "Treat the waitlist as uncertain and preserve a workable enrollment path.", "After a waitlist decision.", ["Accept place decision", "Official instructions", "Current enrollment option", "Deposit deadline", "Financial uncertainty", "Material update", "Continued interest", "Closure date"], ["Treating the waitlist as an expected admit", "Failing to deposit elsewhere"]],
  ["decision-comparison", "Decision-comparison worksheet", "Compare admitted options across education, life, support, and cost.", "After admission and aid offers are complete.", ["Academic model", "Program access", "Community", "Support", "Housing", "Location", "Net cost", "Debt", "Aid renewal", "Student preference", "Unanswered question"], ["Comparing rankings instead of conditions", "Comparing grants without total cost"]],
  ["annual-policy-review", "Consultant annual policy-review checklist", "Review cycle-sensitive sources systematically and archive outdated records.", "Before each application cycle and before high-stakes advice.", ["Institution", "Policy category", "Application cycle", "Official URL", "Status", "Exact dates", "Last reviewed", "Next review", "Archived prior record", "Reviewer notes"], ["Using a blog as final authority", "Silently carrying a policy forward"]],
];

const rawToolkit: ToolkitItem[] = seeds.map(([id, title, purpose, whenToUse, fields, mistakes]) => ({
  id,
  title,
  purpose,
  whenToUse,
  consultantInstructions: "Open this worksheet with the student or family, state its purpose, record only information needed for that purpose, identify unresolved questions, and finish with named owners and dates.",
  studentInstructions: "Use your own words. If a question does not fit your circumstances, mark it not applicable rather than inventing an answer.",
  mistakes,
  fields,
}));

export const toolkit = validateCollection(toolkitSchema, rawToolkit);

export function getToolkitItem(id: string) {
  return toolkit.find((item) => item.id === id);
}
